name: Check Firebase InAppMessaging Version

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at 00:00 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          repository: AhmedNader65/firebase-android-sdk
          path: your-repo
          ref: main
          fetch-depth: 0

      - name: Checkout original repository with sparse checkout
        uses: actions/checkout@v4
        with:
          repository: firebase/firebase-android-sdk
          path: original-repo
          fetch-depth: 0
          sparse-checkout: |
            firebase-inappmessaging/
          sparse-checkout-cone-mode: false

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Find latest release branch
        id: find-branch
        run: |
          cd original-repo
          echo "Listing remote branches:"
          git branch -r
          LATEST_BRANCH=$(git for-each-ref --sort=-committerdate refs/remotes/origin/ --format='%(refname:short)' | grep -E 'releases/m[0-9]+\.release$' | grep -v '\-test' | head -n 1 | sed 's|origin/||' || echo "main")
          if [ -z "$LATEST_BRANCH" ]; then
          LATEST_BRANCH="main"
          fi
          echo "Latest release branch: $LATEST_BRANCH"
          git checkout $LATEST_BRANCH || { echo "Failed to checkout $LATEST_BRANCH"; exit 1; }
          echo "branch=$LATEST_BRANCH" >> $GITHUB_OUTPUT
        shell: bash

      - name: Compare versions
        id: compare-versions
        run: |
          YOUR_VERSION=$(grep '^version=' your-repo/firebase-inappmessaging/gradle.properties | cut -d'=' -f2 || echo "0.0.0")
          ORIGINAL_VERSION=$(grep '^version=' original-repo/firebase-inappmessaging/gradle.properties | cut -d'=' -f2 || echo "0.0.0")
          echo "Your version: $YOUR_VERSION"
          echo "Original version: $ORIGINAL_VERSION"
          if [ "$(printf '%s\n' "$YOUR_VERSION" "$ORIGINAL_VERSION" | sort -V | head -n1)" = "$YOUR_VERSION" ] && [ "$YOUR_VERSION" != "$ORIGINAL_VERSION" ]; then
            echo "Versions differ. Proceeding with update."
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$ORIGINAL_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same. No update needed."
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Pull and merge changes
        id: pull-changes
        if: steps.compare-versions.outputs.update_needed == 'true'
        run: |
          # Move to your repository directory
          cd your-repo

          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Create a new branch for our update
          git checkout -b update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}

          # Add the original repo as a remote to fetch from it
          git remote add firebase-original ../original-repo
          git fetch firebase-original ${{ steps.find-branch.outputs.branch }}

          # Try to merge only the firebase-inappmessaging directory from the original repo
          echo "Attempting to merge firebase-inappmessaging from ${{ steps.find-branch.outputs.branch }}"
          if git merge -X subtree=firebase-inappmessaging firebase-original/${{ steps.find-branch.outputs.branch }} --allow-unrelated-histories; then
            echo "Merge successful"
            echo "conflict_detected=false" >> $GITHUB_OUTPUT

            # Update version in gradle.properties
            sed -i "s/version=.*/version=${{ steps.compare-versions.outputs.new_version }}/" firebase-inappmessaging/gradle.properties

            # Commit version update
            git commit -am "Update firebase-inappmessaging to version ${{ steps.compare-versions.outputs.new_version }}"

            # Push changes to main
            git checkout main
            git merge --no-ff update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}
            git push origin main

            # Create tag for JitPack
            git tag v${{ steps.compare-versions.outputs.new_version }}
            git push origin v${{ steps.compare-versions.outputs.new_version }}
            echo "Created and pushed tag v${{ steps.compare-versions.outputs.new_version }} for JitPack."
          else
            echo "Merge conflict detected!"
            echo "conflict_detected=true" >> $GITHUB_OUTPUT
            git merge --abort
            git checkout main
            git branch -D update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}
          fi

          # Clean up the temporary remote
          git remote remove firebase-original
        shell: bash

      - name: Notify on merge conflict
        if: steps.compare-versions.outputs.update_needed == 'true' && steps.pull-changes.outputs.conflict_detected == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const title = `Merge Conflict: firebase-inappmessaging v${{ steps.compare-versions.outputs.new_version }}`;
            const body = `A merge conflict occurred while trying to update firebase-inappmessaging to version ${{ steps.compare-versions.outputs.new_version }} from branch ${{ steps.find-branch.outputs.branch }}. Please resolve manually.`;
            await github.rest.issues.create({
              owner,
              repo,
              title,
              body
            });
            console.log('Created issue for merge conflict.');

      - name: JitPack info
        if: steps.compare-versions.outputs.update_needed == 'true' && steps.pull-changes.outputs.conflict_detected == 'false'
        run: |
          echo "JitPack will now build:"
          echo "Implementation URL:"
          echo "implementation 'com.github.AhmedNader65:firebase-android-sdk:v${{ steps.compare-versions.outputs.new_version }}'"
          echo "Build status: https://jitpack.io/#AhmedNader65/firebase-android-sdk/v${{ steps.compare-versions.outputs.new_version }}"
        shell: bash