name: Check Firebase InAppMessaging Version

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at 00:00 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          repository: AhmedNader65/firebase-android-sdk
          path: your-repo
          ref: main
          fetch-depth: 0

      - name: Checkout original repository with sparse checkout
        uses: actions/checkout@v4
        with:
          repository: firebase/firebase-android-sdk
          path: original-repo
          fetch-depth: 0
          sparse-checkout: |
            firebase-inappmessaging/
          sparse-checkout-cone-mode: false

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Find latest release branch
        id: find-branch
        run: |
          cd original-repo
          echo "Listing remote branches:"
          git branch -r
          LATEST_BRANCH=$(git for-each-ref --sort=-committerdate refs/remotes/origin/ --format='%(refname:short)' | grep -E 'releases/m[0-9]+\.release$' | grep -v '\-test' | head -n 1 | sed 's|origin/||' || echo "main")
          if [ -z "$LATEST_BRANCH" ]; then
          LATEST_BRANCH="main"
          fi
          echo "Latest release branch: $LATEST_BRANCH"
          git checkout $LATEST_BRANCH || { echo "Failed to checkout $LATEST_BRANCH"; exit 1; }
          echo "branch=$LATEST_BRANCH" >> $GITHUB_OUTPUT
        shell: bash

      - name: Compare versions
        id: compare-versions
        run: |
          YOUR_VERSION=$(grep '^version=' your-repo/firebase-inappmessaging/gradle.properties | cut -d'=' -f2 || echo "0.0.0")
          ORIGINAL_VERSION=$(grep '^version=' original-repo/firebase-inappmessaging/gradle.properties | cut -d'=' -f2 || echo "0.0.0")
          echo "Your version: $YOUR_VERSION"
          echo "Original version: $ORIGINAL_VERSION"
          if [ "$(printf '%s\n' "$YOUR_VERSION" "$ORIGINAL_VERSION" | sort -V | head -n1)" = "$YOUR_VERSION" ] && [ "$YOUR_VERSION" != "$ORIGINAL_VERSION" ]; then
            echo "Versions differ. Proceeding with update."
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$ORIGINAL_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Versions are the same. No update needed."
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      # Replace the read-tree section with this
      - name: Update from original repo and apply patch
        id: update-repo
        if: steps.compare-versions.outputs.update_needed == 'true'
        run: |
          cd your-repo

          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Find the common base between our repo and the original repo
          echo "Finding common base commit between our repo and original repo..."
          git remote add firebase-original ../original-repo || true
          git fetch firebase-original ${{ steps.find-branch.outputs.branch }} --no-tags
          echo "Fetched firebase-original ${{ steps.find-branch.outputs.branch }}"
          
          # Find the merge base or earliest commit if none exists
          if git merge-base HEAD firebase-original/${{ steps.find-branch.outputs.branch }} &>/dev/null; then
          LAST_MERGE_COMMIT=$(git merge-base HEAD firebase-original/${{ steps.find-branch.outputs.branch }})
            echo "Found common ancestor: $LAST_MERGE_COMMIT"
          else
            echo "No common ancestor found, using current HEAD as base"
            LAST_MERGE_COMMIT=$(git rev-parse HEAD)
          fi
          
          # Create a patch of our customizations since that commit
          echo "Creating patch of our customizations in firebase-inappmessaging directory only..."
          git format-patch $LAST_MERGE_COMMIT --stdout -- firebase-inappmessaging/ > ../our-changes.patch

          # Create a new branch for the update
          git checkout -b update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}

          # Get the latest from the original repo
          echo "Fetching latest from original repo..."
          git remote add firebase-original ../original-repo
          git fetch firebase-original

          # Reset the firebase-inappmessaging directory to match the original repo
          echo "Resetting to match original repo..."
          git checkout firebase-original/${{ steps.find-branch.outputs.branch }} -- firebase-inappmessaging/

          # Update version in gradle.properties
          sed -i "s/version=.*/version=${{ steps.compare-versions.outputs.new_version }}/" firebase-inappmessaging/gradle.properties
          git add firebase-inappmessaging/gradle.properties

          # Commit the updated files from original repo
          git commit -m "Update firebase-inappmessaging to version ${{ steps.compare-versions.outputs.new_version }}"

          # Try to apply our custom changes on top
          echo "Applying our customizations..."
          if git apply --check ../our-changes.patch; then
            git apply ../our-changes.patch
            git add .
            git commit -m "Applied our customizations to firebase-inappmessaging ${{ steps.compare-versions.outputs.new_version }}"

            # Try to merge into main
            git checkout main
            if git merge --no-ff update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}; then
              echo "Merge successful."
              echo "conflict_detected=false" >> $GITHUB_OUTPUT
              git push origin main

              # Create tag for JitPack
              git tag v${{ steps.compare-versions.outputs.new_version }}
              git push origin v${{ steps.compare-versions.outputs.new_version }}
              echo "Created and pushed tag v${{ steps.compare-versions.outputs.new_version }} for JitPack."
            else
              echo "Merge conflict detected!"
              echo "conflict_detected=true" >> $GITHUB_OUTPUT
              git merge --abort
              git checkout main
              git branch -D update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}
            fi
          else
            echo "Cannot apply patch cleanly, there are conflicts"
            echo "conflict_detected=true" >> $GITHUB_OUTPUT
            git reset --hard HEAD
            git checkout main
            git branch -D update-firebase-inappmessaging-${{ steps.compare-versions.outputs.new_version }}
          fi

          # Clean up
          git remote remove firebase-original
        shell: bash

      - name: Notify on merge conflict
        if: steps.compare-versions.outputs.update_needed == 'true' && steps.pull-changes.outputs.conflict_detected == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const title = `Merge Conflict: firebase-inappmessaging v${{ steps.compare-versions.outputs.new_version }}`;
            const body = `A merge conflict occurred while trying to update firebase-inappmessaging to version ${{ steps.compare-versions.outputs.new_version }} from branch ${{ steps.find-branch.outputs.branch }}. Please resolve manually.`;
            await github.rest.issues.create({
              owner,
              repo,
              title,
              body
            });
            console.log('Created issue for merge conflict.');

      - name: JitPack info
        if: steps.compare-versions.outputs.update_needed == 'true' && steps.pull-changes.outputs.conflict_detected == 'false'
        run: |
          echo "JitPack will now build:"
          echo "Implementation URL:"
          echo "implementation 'com.github.AhmedNader65:firebase-android-sdk:v${{ steps.compare-versions.outputs.new_version }}'"
          echo "Build status: https://jitpack.io/#AhmedNader65/firebase-android-sdk/v${{ steps.compare-versions.outputs.new_version }}"
        shell: bash